### ISSUE TITLE
Calibration not starting in container with tidl 8.2

### ISSUE THREAD

**Issue by RGBsrs** [WasabiFan/tidl-custom-model-demo#6]
When I try compile yolov5 640 px from ti model zoo it do compilation step but calibration not starts. 
And files detections_tidl_io_1.bin,  detections_tidl_net.bin not created in tidl_output directory. 

But if I use container from branch edgeai-8-6 calibration starts and this files exists in output. But I cant use whis compiled model in my **BeagleBone AI-64** with **bbai64-debian-11.6-xfce-edgeai-arm64-2023-01-02-10gb.img.xz** image

**Comment by WasabiFan** [comment]
Can you show output that illustrates the behavior? By _not starting_, do you mean the program hangs indefinitely?

**Comment by WasabiFan** [comment]
That it works for 8.6 but not 8.2 suggests it may be a TI bug, but hopefully the output gives more info.

**Comment by RGBsrs** [comment]
Sure. 
"By not starting, do you mean the program hangs indefinitely" - no, program completed successfully, but without calibraion process logs in terminal window.
Here output files of container with tidl 8.2
![image](https://github.com/WasabiFan/tidl-yolov5-custom-model-demo/assets/50082968/ddbfe501-997e-4ffd-8dff-54818d58e124)
And output files of container with tidl 8.6

**Comment by RGBsrs** [comment]
Sure. 
"By not starting, do you mean the program hangs indefinitely" - no, program completed successfully, but without calibraion process logs in terminal window.
Here output files of container with tidl 8.2
![image](https://github.com/WasabiFan/tidl-yolov5-custom-model-demo/assets/50082968/ddbfe501-997e-4ffd-8dff-54818d58e124)
And output files of container with tidl 8.6
![image](https://github.com/WasabiFan/tidl-yolov5-custom-model-demo/assets/50082968/74556eef-a43e-49bc-82e2-53d9d5464230)
This operations are exist in both tidls
![image](https://github.com/WasabiFan/tidl-yolov5-custom-model-demo/assets/50082968/973a8b52-0443-43f7-ba97-23d216f529b6)
Also here example of tidl 8.6 console output which not exist when I try use tidl 8.2
![image](https://github.com/WasabiFan/tidl-yolov5-custom-model-demo/assets/50082968/bb292daf-24da-4645-9fcb-92d6bf8e1655)

**Comment by RGBsrs** [comment]
I found that this problem is only with big input size of model. Another one with smaller input compiled successfully and much faster.

**Comment by MGN-GIT** [comment]
> I found that this problem is only with big input size of model. Another one with smaller input compiled successfully and much faster.

hey man can please help me out in compiling model of edge yolov5

**Comment by RGBsrs** [comment]
Yes. What problem you have?

**Comment by MGN-GIT** [comment]
> Yes. What problem you have?

i dont know what is the exact step to compile, can you please each and every step ? probably can you please give insta or any contact detail to communicate with? if possible

**Comment by MGN-GIT** [comment]
i am intrested in compiling edge yolo ti lite models using edgeai tidl tools or edge ai benchmark

**Comment by RGBsrs** [comment]
I think that owner of this repo can help more. I only use his instructions.
