### ISSUE TITLE
Calibration not starting in container with tidl

### ISSUE THREAD

**Issue by rafajafa** [WasabiFan/tidl-custom-model-demo#7]
Hi, thank you for your work.
When I try compile yolov5 model from ti model zoo it did the compilation step but calibration not starts. It stops right after it finish inference shape. However, when i feed it with a calibration images folder with no image in it, the code run just fine. The output file is similar to another issues by user "RGBsrs' in tidl 8.2 with only the allowed node, onnxrtdata and tempDir showing. I have tried a smaller model (384*384) but the same issue occurs. I am using tidl 8.6 (08_06_00_00).

**Comment by WasabiFan** [comment]
Unfortunately I have no visibility into what TIDL is doing internally. When I ran into similar issues in the past I just iterated via trial-and-error until the problem went away. It's incredibly buggy software. If passing an empty calibration directory solves it, then I recommend you do that. I have no idea what side-effects that may have.

**Comment by rafajafa** [comment]
Thanks for the replay. I manage to compile the model by not using docker and turn off hyper v on my window computer, so it could be something wrong with me setting up the docker environment or hyper v stopping AVX from running on my Linux VM.
